# Generated by Django 3.1.3 on 2023-06-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='유저 아이디')),
                ('password', models.CharField(max_length=128, verbose_name='유저 비밀번호')),
                ('nickname', models.CharField(max_length=16, unique=True, verbose_name='유저 닉네임')),
                ('email', models.EmailField(max_length=128, unique=True, verbose_name='유저 이메일')),
                ('address', models.CharField(max_length=128, verbose_name='유저 주소')),
                ('phone', models.CharField(max_length=128, unique=True, verbose_name='유저 전화번호')),
            ],
        ),
    ]
