# Generated by Django 3.1.3 on 2023-06-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=200)),
                ('fMenu', models.CharField(max_length=200)),
                ('select_date', models.DateTimeField()),
            ],
        ),
    ]
