# Generated by Django 3.1.3 on 2023-06-23 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0005_auto_20230623_1509'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
